- vgg.nn.0.conv.weight
- vgg.nn.0.conv.bias
- vgg.nn.0.bn.weight
- vgg.nn.0.bn.bias
- vgg.nn.1.conv.weight
- vgg.nn.1.conv.bias
- vgg.nn.1.bn.weight
- vgg.nn.1.bn.bias
- vgg.nn.3.conv.weight
- vgg.nn.3.conv.bias
- vgg.nn.3.bn.weight
- vgg.nn.3.bn.bias
- vgg.nn.4.conv.weight
- vgg.nn.4.conv.bias
- vgg.nn.4.bn.weight
- vgg.nn.4.bn.bias
- vgg.nn.6.conv.weight
- vgg.nn.6.conv.bias
- vgg.nn.6.bn.weight
- vgg.nn.6.bn.bias
- vgg.nn.7.conv.weight
- vgg.nn.7.conv.bias
- vgg.nn.7.bn.weight
- vgg.nn.7.bn.bias
- vgg.nn.8.conv.weight
- vgg.nn.8.conv.bias
- vgg.nn.8.bn.weight
- vgg.nn.8.bn.bias
- vgg.nn.10.conv.weight
- vgg.nn.10.conv.bias
- vgg.nn.10.bn.weight
- vgg.nn.10.bn.bias
- vgg.nn.11.conv.weight
- vgg.nn.11.conv.bias
- vgg.nn.11.bn.weight
- vgg.nn.11.bn.bias
- vgg.nn.12.conv.weight
- vgg.nn.12.conv.bias
- vgg.nn.12.bn.weight
- vgg.nn.12.bn.bias
- vgg.nn.14.conv.weight
- vgg.nn.14.conv.bias
- vgg.nn.14.bn.weight
- vgg.nn.14.bn.bias
- vgg.nn.15.conv.weight
- vgg.nn.15.conv.bias
- vgg.nn.15.bn.weight
- vgg.nn.15.bn.bias
- vgg.nn.16.conv.weight
- vgg.nn.16.conv.bias
- vgg.nn.16.bn.weight
- vgg.nn.16.bn.bias
- vgg.fc.weight
- vgg.fc.bias