- layer0.0.weight
- layer1.0.conv1.weight
- layer1.0.conv2.weight
- layer1.1.conv1.weight
- layer1.1.conv2.weight
- layer2.0.conv1.weight
- layer2.0.conv2.weight
- layer2.0.downsample.0.weight
- layer2.1.conv1.weight
- layer2.1.conv2.weight
- layer3.0.conv1.weight
- layer3.0.conv2.weight
- layer3.0.downsample.0.weight
- layer3.1.conv1.weight
- layer3.1.conv2.weight
- layer4.0.conv1.weight
- layer4.0.conv2.weight
- layer4.0.downsample.0.weight
- layer4.1.conv1.weight
- layer4.1.conv2.weight