- net.encoder.conv1.weight
- net.encoder.bn1.weight
- net.encoder.bn1.bias
- net.encoder.layer1.0.conv1.weight
- net.encoder.layer1.0.bn1.weight
- net.encoder.layer1.0.bn1.bias
- net.encoder.layer1.0.conv2.weight
- net.encoder.layer1.0.bn2.weight
- net.encoder.layer1.0.bn2.bias
- net.encoder.layer1.0.conv3.weight
- net.encoder.layer1.0.bn3.weight
- net.encoder.layer1.0.bn3.bias
- net.encoder.layer1.0.downsample.0.weight
- net.encoder.layer1.0.downsample.1.weight
- net.encoder.layer1.0.downsample.1.bias
- net.encoder.layer1.1.conv1.weight
- net.encoder.layer1.1.bn1.weight
- net.encoder.layer1.1.bn1.bias
- net.encoder.layer1.1.conv2.weight
- net.encoder.layer1.1.bn2.weight
- net.encoder.layer1.1.bn2.bias
- net.encoder.layer1.1.conv3.weight
- net.encoder.layer1.1.bn3.weight
- net.encoder.layer1.1.bn3.bias
- net.encoder.layer1.2.conv1.weight
- net.encoder.layer1.2.bn1.weight
- net.encoder.layer1.2.bn1.bias
- net.encoder.layer1.2.conv2.weight
- net.encoder.layer1.2.bn2.weight
- net.encoder.layer1.2.bn2.bias
- net.encoder.layer1.2.conv3.weight
- net.encoder.layer1.2.bn3.weight
- net.encoder.layer1.2.bn3.bias
- net.encoder.layer2.0.conv1.weight
- net.encoder.layer2.0.bn1.weight
- net.encoder.layer2.0.bn1.bias
- net.encoder.layer2.0.conv2.weight
- net.encoder.layer2.0.bn2.weight
- net.encoder.layer2.0.bn2.bias
- net.encoder.layer2.0.conv3.weight
- net.encoder.layer2.0.bn3.weight
- net.encoder.layer2.0.bn3.bias
- net.encoder.layer2.0.downsample.0.weight
- net.encoder.layer2.0.downsample.1.weight
- net.encoder.layer2.0.downsample.1.bias
- net.encoder.layer2.1.conv1.weight
- net.encoder.layer2.1.bn1.weight
- net.encoder.layer2.1.bn1.bias
- net.encoder.layer2.1.conv2.weight
- net.encoder.layer2.1.bn2.weight
- net.encoder.layer2.1.bn2.bias
- net.encoder.layer2.1.conv3.weight
- net.encoder.layer2.1.bn3.weight
- net.encoder.layer2.1.bn3.bias
- net.encoder.layer2.2.conv1.weight
- net.encoder.layer2.2.bn1.weight
- net.encoder.layer2.2.bn1.bias
- net.encoder.layer2.2.conv2.weight
- net.encoder.layer2.2.bn2.weight
- net.encoder.layer2.2.bn2.bias
- net.encoder.layer2.2.conv3.weight
- net.encoder.layer2.2.bn3.weight
- net.encoder.layer2.2.bn3.bias
- net.encoder.layer2.3.conv1.weight
- net.encoder.layer2.3.bn1.weight
- net.encoder.layer2.3.bn1.bias
- net.encoder.layer2.3.conv2.weight
- net.encoder.layer2.3.bn2.weight
- net.encoder.layer2.3.bn2.bias
- net.encoder.layer2.3.conv3.weight
- net.encoder.layer2.3.bn3.weight
- net.encoder.layer2.3.bn3.bias
- net.encoder.layer3.0.conv1.weight
- net.encoder.layer3.0.bn1.weight
- net.encoder.layer3.0.bn1.bias
- net.encoder.layer3.0.conv2.weight
- net.encoder.layer3.0.bn2.weight
- net.encoder.layer3.0.bn2.bias
- net.encoder.layer3.0.conv3.weight
- net.encoder.layer3.0.bn3.weight
- net.encoder.layer3.0.bn3.bias
- net.encoder.layer3.0.downsample.0.weight
- net.encoder.layer3.0.downsample.1.weight
- net.encoder.layer3.0.downsample.1.bias
- net.encoder.layer3.1.conv1.weight
- net.encoder.layer3.1.bn1.weight
- net.encoder.layer3.1.bn1.bias
- net.encoder.layer3.1.conv2.weight
- net.encoder.layer3.1.bn2.weight
- net.encoder.layer3.1.bn2.bias
- net.encoder.layer3.1.conv3.weight
- net.encoder.layer3.1.bn3.weight
- net.encoder.layer3.1.bn3.bias
- net.encoder.layer3.2.conv1.weight
- net.encoder.layer3.2.bn1.weight
- net.encoder.layer3.2.bn1.bias
- net.encoder.layer3.2.conv2.weight
- net.encoder.layer3.2.bn2.weight
- net.encoder.layer3.2.bn2.bias
- net.encoder.layer3.2.conv3.weight
- net.encoder.layer3.2.bn3.weight
- net.encoder.layer3.2.bn3.bias
- net.encoder.layer3.3.conv1.weight
- net.encoder.layer3.3.bn1.weight
- net.encoder.layer3.3.bn1.bias
- net.encoder.layer3.3.conv2.weight
- net.encoder.layer3.3.bn2.weight
- net.encoder.layer3.3.bn2.bias
- net.encoder.layer3.3.conv3.weight
- net.encoder.layer3.3.bn3.weight
- net.encoder.layer3.3.bn3.bias
- net.encoder.layer3.4.conv1.weight
- net.encoder.layer3.4.bn1.weight
- net.encoder.layer3.4.bn1.bias
- net.encoder.layer3.4.conv2.weight
- net.encoder.layer3.4.bn2.weight
- net.encoder.layer3.4.bn2.bias
- net.encoder.layer3.4.conv3.weight
- net.encoder.layer3.4.bn3.weight
- net.encoder.layer3.4.bn3.bias
- net.encoder.layer3.5.conv1.weight
- net.encoder.layer3.5.bn1.weight
- net.encoder.layer3.5.bn1.bias
- net.encoder.layer3.5.conv2.weight
- net.encoder.layer3.5.bn2.weight
- net.encoder.layer3.5.bn2.bias
- net.encoder.layer3.5.conv3.weight
- net.encoder.layer3.5.bn3.weight
- net.encoder.layer3.5.bn3.bias
- net.encoder.layer4.0.conv1.weight
- net.encoder.layer4.0.bn1.weight
- net.encoder.layer4.0.bn1.bias
- net.encoder.layer4.0.conv2.weight
- net.encoder.layer4.0.bn2.weight
- net.encoder.layer4.0.bn2.bias
- net.encoder.layer4.0.conv3.weight
- net.encoder.layer4.0.bn3.weight
- net.encoder.layer4.0.bn3.bias
- net.encoder.layer4.0.downsample.0.weight
- net.encoder.layer4.0.downsample.1.weight
- net.encoder.layer4.0.downsample.1.bias
- net.encoder.layer4.1.conv1.weight
- net.encoder.layer4.1.bn1.weight
- net.encoder.layer4.1.bn1.bias
- net.encoder.layer4.1.conv2.weight
- net.encoder.layer4.1.bn2.weight
- net.encoder.layer4.1.bn2.bias
- net.encoder.layer4.1.conv3.weight
- net.encoder.layer4.1.bn3.weight
- net.encoder.layer4.1.bn3.bias
- net.encoder.layer4.2.conv1.weight
- net.encoder.layer4.2.bn1.weight
- net.encoder.layer4.2.bn1.bias
- net.encoder.layer4.2.conv2.weight
- net.encoder.layer4.2.bn2.weight
- net.encoder.layer4.2.bn2.bias
- net.encoder.layer4.2.conv3.weight
- net.encoder.layer4.2.bn3.weight
- net.encoder.layer4.2.bn3.bias
- net.decoder.aspp.0.convs.0.0.weight
- net.decoder.aspp.0.convs.0.1.weight
- net.decoder.aspp.0.convs.0.1.bias
- net.decoder.aspp.0.convs.1.0.0.weight
- net.decoder.aspp.0.convs.1.0.1.weight
- net.decoder.aspp.0.convs.1.1.weight
- net.decoder.aspp.0.convs.1.1.bias
- net.decoder.aspp.0.convs.2.0.0.weight
- net.decoder.aspp.0.convs.2.0.1.weight
- net.decoder.aspp.0.convs.2.1.weight
- net.decoder.aspp.0.convs.2.1.bias
- net.decoder.aspp.0.convs.3.0.0.weight
- net.decoder.aspp.0.convs.3.0.1.weight
- net.decoder.aspp.0.convs.3.1.weight
- net.decoder.aspp.0.convs.3.1.bias
- net.decoder.aspp.0.convs.4.1.weight
- net.decoder.aspp.0.convs.4.2.weight
- net.decoder.aspp.0.convs.4.2.bias
- net.decoder.aspp.0.project.0.weight
- net.decoder.aspp.0.project.1.weight
- net.decoder.aspp.0.project.1.bias
- net.decoder.aspp.1.0.weight
- net.decoder.aspp.1.1.weight
- net.decoder.aspp.2.weight
- net.decoder.aspp.2.bias
- net.decoder.block1.0.weight
- net.decoder.block1.1.weight
- net.decoder.block1.1.bias
- net.decoder.block2.0.0.weight
- net.decoder.block2.0.1.weight
- net.decoder.block2.1.weight
- net.decoder.block2.1.bias
- net.segmentation_head.0.weight
- net.segmentation_head.0.bias