- model.conv1.weight
- model.conv2.weight
- model.layer1.0.conv1.weight
- model.layer1.0.conv2.weight
- model.layer1.0.conv3.weight
- model.layer1.0.downsample.0.weight
- model.layer1.1.conv1.weight
- model.layer1.1.conv2.weight
- model.layer1.1.conv3.weight
- model.layer1.2.conv1.weight
- model.layer1.2.conv2.weight
- model.layer1.2.conv3.weight
- model.layer1.3.conv1.weight
- model.layer1.3.conv2.weight
- model.layer1.3.conv3.weight
- model.transition1.0.0.weight
- model.transition1.1.0.0.weight
- model.stage2.0.branches.0.0.conv1.weight
- model.stage2.0.branches.0.0.conv2.weight
- model.stage2.0.branches.0.1.conv1.weight
- model.stage2.0.branches.0.1.conv2.weight
- model.stage2.0.branches.0.2.conv1.weight
- model.stage2.0.branches.0.2.conv2.weight
- model.stage2.0.branches.0.3.conv1.weight
- model.stage2.0.branches.0.3.conv2.weight
- model.stage2.0.branches.1.0.conv1.weight
- model.stage2.0.branches.1.0.conv2.weight
- model.stage2.0.branches.1.1.conv1.weight
- model.stage2.0.branches.1.1.conv2.weight
- model.stage2.0.branches.1.2.conv1.weight
- model.stage2.0.branches.1.2.conv2.weight
- model.stage2.0.branches.1.3.conv1.weight
- model.stage2.0.branches.1.3.conv2.weight
- model.stage2.0.fuse_layers.0.1.0.weight
- model.stage2.0.fuse_layers.1.0.0.0.weight
- model.transition2.2.0.0.weight
- model.stage3.0.branches.0.0.conv1.weight
- model.stage3.0.branches.0.0.conv2.weight
- model.stage3.0.branches.0.1.conv1.weight
- model.stage3.0.branches.0.1.conv2.weight
- model.stage3.0.branches.0.2.conv1.weight
- model.stage3.0.branches.0.2.conv2.weight
- model.stage3.0.branches.0.3.conv1.weight
- model.stage3.0.branches.0.3.conv2.weight
- model.stage3.0.branches.1.0.conv1.weight
- model.stage3.0.branches.1.0.conv2.weight
- model.stage3.0.branches.1.1.conv1.weight
- model.stage3.0.branches.1.1.conv2.weight
- model.stage3.0.branches.1.2.conv1.weight
- model.stage3.0.branches.1.2.conv2.weight
- model.stage3.0.branches.1.3.conv1.weight
- model.stage3.0.branches.1.3.conv2.weight
- model.stage3.0.branches.2.0.conv1.weight
- model.stage3.0.branches.2.0.conv2.weight
- model.stage3.0.branches.2.1.conv1.weight
- model.stage3.0.branches.2.1.conv2.weight
- model.stage3.0.branches.2.2.conv1.weight
- model.stage3.0.branches.2.2.conv2.weight
- model.stage3.0.branches.2.3.conv1.weight
- model.stage3.0.branches.2.3.conv2.weight
- model.stage3.0.fuse_layers.0.1.0.weight
- model.stage3.0.fuse_layers.0.2.0.weight
- model.stage3.0.fuse_layers.1.0.0.0.weight
- model.stage3.0.fuse_layers.1.2.0.weight
- model.stage3.0.fuse_layers.2.0.0.0.weight
- model.stage3.0.fuse_layers.2.0.1.0.weight
- model.stage3.0.fuse_layers.2.1.0.0.weight
- model.stage3.1.branches.0.0.conv1.weight
- model.stage3.1.branches.0.0.conv2.weight
- model.stage3.1.branches.0.1.conv1.weight
- model.stage3.1.branches.0.1.conv2.weight
- model.stage3.1.branches.0.2.conv1.weight
- model.stage3.1.branches.0.2.conv2.weight
- model.stage3.1.branches.0.3.conv1.weight
- model.stage3.1.branches.0.3.conv2.weight
- model.stage3.1.branches.1.0.conv1.weight
- model.stage3.1.branches.1.0.conv2.weight
- model.stage3.1.branches.1.1.conv1.weight
- model.stage3.1.branches.1.1.conv2.weight
- model.stage3.1.branches.1.2.conv1.weight
- model.stage3.1.branches.1.2.conv2.weight
- model.stage3.1.branches.1.3.conv1.weight
- model.stage3.1.branches.1.3.conv2.weight
- model.stage3.1.branches.2.0.conv1.weight
- model.stage3.1.branches.2.0.conv2.weight
- model.stage3.1.branches.2.1.conv1.weight
- model.stage3.1.branches.2.1.conv2.weight
- model.stage3.1.branches.2.2.conv1.weight
- model.stage3.1.branches.2.2.conv2.weight
- model.stage3.1.branches.2.3.conv1.weight
- model.stage3.1.branches.2.3.conv2.weight
- model.stage3.1.fuse_layers.0.1.0.weight
- model.stage3.1.fuse_layers.0.2.0.weight
- model.stage3.1.fuse_layers.1.0.0.0.weight
- model.stage3.1.fuse_layers.1.2.0.weight
- model.stage3.1.fuse_layers.2.0.0.0.weight
- model.stage3.1.fuse_layers.2.0.1.0.weight
- model.stage3.1.fuse_layers.2.1.0.0.weight
- model.stage3.2.branches.0.0.conv1.weight
- model.stage3.2.branches.0.0.conv2.weight
- model.stage3.2.branches.0.1.conv1.weight
- model.stage3.2.branches.0.1.conv2.weight
- model.stage3.2.branches.0.2.conv1.weight
- model.stage3.2.branches.0.2.conv2.weight
- model.stage3.2.branches.0.3.conv1.weight
- model.stage3.2.branches.0.3.conv2.weight
- model.stage3.2.branches.1.0.conv1.weight
- model.stage3.2.branches.1.0.conv2.weight
- model.stage3.2.branches.1.1.conv1.weight
- model.stage3.2.branches.1.1.conv2.weight
- model.stage3.2.branches.1.2.conv1.weight
- model.stage3.2.branches.1.2.conv2.weight
- model.stage3.2.branches.1.3.conv1.weight
- model.stage3.2.branches.1.3.conv2.weight
- model.stage3.2.branches.2.0.conv1.weight
- model.stage3.2.branches.2.0.conv2.weight
- model.stage3.2.branches.2.1.conv1.weight
- model.stage3.2.branches.2.1.conv2.weight
- model.stage3.2.branches.2.2.conv1.weight
- model.stage3.2.branches.2.2.conv2.weight
- model.stage3.2.branches.2.3.conv1.weight
- model.stage3.2.branches.2.3.conv2.weight
- model.stage3.2.fuse_layers.0.1.0.weight
- model.stage3.2.fuse_layers.0.2.0.weight
- model.stage3.2.fuse_layers.1.0.0.0.weight
- model.stage3.2.fuse_layers.1.2.0.weight
- model.stage3.2.fuse_layers.2.0.0.0.weight
- model.stage3.2.fuse_layers.2.0.1.0.weight
- model.stage3.2.fuse_layers.2.1.0.0.weight
- model.stage3.3.branches.0.0.conv1.weight
- model.stage3.3.branches.0.0.conv2.weight
- model.stage3.3.branches.0.1.conv1.weight
- model.stage3.3.branches.0.1.conv2.weight
- model.stage3.3.branches.0.2.conv1.weight
- model.stage3.3.branches.0.2.conv2.weight
- model.stage3.3.branches.0.3.conv1.weight
- model.stage3.3.branches.0.3.conv2.weight
- model.stage3.3.branches.1.0.conv1.weight
- model.stage3.3.branches.1.0.conv2.weight
- model.stage3.3.branches.1.1.conv1.weight
- model.stage3.3.branches.1.1.conv2.weight
- model.stage3.3.branches.1.2.conv1.weight
- model.stage3.3.branches.1.2.conv2.weight
- model.stage3.3.branches.1.3.conv1.weight
- model.stage3.3.branches.1.3.conv2.weight
- model.stage3.3.branches.2.0.conv1.weight
- model.stage3.3.branches.2.0.conv2.weight
- model.stage3.3.branches.2.1.conv1.weight
- model.stage3.3.branches.2.1.conv2.weight
- model.stage3.3.branches.2.2.conv1.weight
- model.stage3.3.branches.2.2.conv2.weight
- model.stage3.3.branches.2.3.conv1.weight
- model.stage3.3.branches.2.3.conv2.weight
- model.stage3.3.fuse_layers.0.1.0.weight
- model.stage3.3.fuse_layers.0.2.0.weight
- model.stage3.3.fuse_layers.1.0.0.0.weight
- model.stage3.3.fuse_layers.1.2.0.weight
- model.stage3.3.fuse_layers.2.0.0.0.weight
- model.stage3.3.fuse_layers.2.0.1.0.weight
- model.stage3.3.fuse_layers.2.1.0.0.weight
- model.transition3.3.0.0.weight
- model.stage4.0.branches.0.0.conv1.weight
- model.stage4.0.branches.0.0.conv2.weight
- model.stage4.0.branches.0.1.conv1.weight
- model.stage4.0.branches.0.1.conv2.weight
- model.stage4.0.branches.0.2.conv1.weight
- model.stage4.0.branches.0.2.conv2.weight
- model.stage4.0.branches.0.3.conv1.weight
- model.stage4.0.branches.0.3.conv2.weight
- model.stage4.0.branches.1.0.conv1.weight
- model.stage4.0.branches.1.0.conv2.weight
- model.stage4.0.branches.1.1.conv1.weight
- model.stage4.0.branches.1.1.conv2.weight
- model.stage4.0.branches.1.2.conv1.weight
- model.stage4.0.branches.1.2.conv2.weight
- model.stage4.0.branches.1.3.conv1.weight
- model.stage4.0.branches.1.3.conv2.weight
- model.stage4.0.branches.2.0.conv1.weight
- model.stage4.0.branches.2.0.conv2.weight
- model.stage4.0.branches.2.1.conv1.weight
- model.stage4.0.branches.2.1.conv2.weight
- model.stage4.0.branches.2.2.conv1.weight
- model.stage4.0.branches.2.2.conv2.weight
- model.stage4.0.branches.2.3.conv1.weight
- model.stage4.0.branches.2.3.conv2.weight
- model.stage4.0.branches.3.0.conv1.weight
- model.stage4.0.branches.3.0.conv2.weight
- model.stage4.0.branches.3.1.conv1.weight
- model.stage4.0.branches.3.1.conv2.weight
- model.stage4.0.branches.3.2.conv1.weight
- model.stage4.0.branches.3.2.conv2.weight
- model.stage4.0.branches.3.3.conv1.weight
- model.stage4.0.branches.3.3.conv2.weight
- model.stage4.0.fuse_layers.0.1.0.weight
- model.stage4.0.fuse_layers.0.2.0.weight
- model.stage4.0.fuse_layers.0.3.0.weight
- model.stage4.0.fuse_layers.1.0.0.0.weight
- model.stage4.0.fuse_layers.1.2.0.weight
- model.stage4.0.fuse_layers.1.3.0.weight
- model.stage4.0.fuse_layers.2.0.0.0.weight
- model.stage4.0.fuse_layers.2.0.1.0.weight
- model.stage4.0.fuse_layers.2.1.0.0.weight
- model.stage4.0.fuse_layers.2.3.0.weight
- model.stage4.0.fuse_layers.3.0.0.0.weight
- model.stage4.0.fuse_layers.3.0.1.0.weight
- model.stage4.0.fuse_layers.3.0.2.0.weight
- model.stage4.0.fuse_layers.3.1.0.0.weight
- model.stage4.0.fuse_layers.3.1.1.0.weight
- model.stage4.0.fuse_layers.3.2.0.0.weight
- model.stage4.1.branches.0.0.conv1.weight
- model.stage4.1.branches.0.0.conv2.weight
- model.stage4.1.branches.0.1.conv1.weight
- model.stage4.1.branches.0.1.conv2.weight
- model.stage4.1.branches.0.2.conv1.weight
- model.stage4.1.branches.0.2.conv2.weight
- model.stage4.1.branches.0.3.conv1.weight
- model.stage4.1.branches.0.3.conv2.weight
- model.stage4.1.branches.1.0.conv1.weight
- model.stage4.1.branches.1.0.conv2.weight
- model.stage4.1.branches.1.1.conv1.weight
- model.stage4.1.branches.1.1.conv2.weight
- model.stage4.1.branches.1.2.conv1.weight
- model.stage4.1.branches.1.2.conv2.weight
- model.stage4.1.branches.1.3.conv1.weight
- model.stage4.1.branches.1.3.conv2.weight
- model.stage4.1.branches.2.0.conv1.weight
- model.stage4.1.branches.2.0.conv2.weight
- model.stage4.1.branches.2.1.conv1.weight
- model.stage4.1.branches.2.1.conv2.weight
- model.stage4.1.branches.2.2.conv1.weight
- model.stage4.1.branches.2.2.conv2.weight
- model.stage4.1.branches.2.3.conv1.weight
- model.stage4.1.branches.2.3.conv2.weight
- model.stage4.1.branches.3.0.conv1.weight
- model.stage4.1.branches.3.0.conv2.weight
- model.stage4.1.branches.3.1.conv1.weight
- model.stage4.1.branches.3.1.conv2.weight
- model.stage4.1.branches.3.2.conv1.weight
- model.stage4.1.branches.3.2.conv2.weight
- model.stage4.1.branches.3.3.conv1.weight
- model.stage4.1.branches.3.3.conv2.weight
- model.stage4.1.fuse_layers.0.1.0.weight
- model.stage4.1.fuse_layers.0.2.0.weight
- model.stage4.1.fuse_layers.0.3.0.weight
- model.stage4.1.fuse_layers.1.0.0.0.weight
- model.stage4.1.fuse_layers.1.2.0.weight
- model.stage4.1.fuse_layers.1.3.0.weight
- model.stage4.1.fuse_layers.2.0.0.0.weight
- model.stage4.1.fuse_layers.2.0.1.0.weight
- model.stage4.1.fuse_layers.2.1.0.0.weight
- model.stage4.1.fuse_layers.2.3.0.weight
- model.stage4.1.fuse_layers.3.0.0.0.weight
- model.stage4.1.fuse_layers.3.0.1.0.weight
- model.stage4.1.fuse_layers.3.0.2.0.weight
- model.stage4.1.fuse_layers.3.1.0.0.weight
- model.stage4.1.fuse_layers.3.1.1.0.weight
- model.stage4.1.fuse_layers.3.2.0.0.weight
- model.stage4.2.branches.0.0.conv1.weight
- model.stage4.2.branches.0.0.conv2.weight
- model.stage4.2.branches.0.1.conv1.weight
- model.stage4.2.branches.0.1.conv2.weight
- model.stage4.2.branches.0.2.conv1.weight
- model.stage4.2.branches.0.2.conv2.weight
- model.stage4.2.branches.0.3.conv1.weight
- model.stage4.2.branches.0.3.conv2.weight
- model.stage4.2.branches.1.0.conv1.weight
- model.stage4.2.branches.1.0.conv2.weight
- model.stage4.2.branches.1.1.conv1.weight
- model.stage4.2.branches.1.1.conv2.weight
- model.stage4.2.branches.1.2.conv1.weight
- model.stage4.2.branches.1.2.conv2.weight
- model.stage4.2.branches.1.3.conv1.weight
- model.stage4.2.branches.1.3.conv2.weight
- model.stage4.2.branches.2.0.conv1.weight
- model.stage4.2.branches.2.0.conv2.weight
- model.stage4.2.branches.2.1.conv1.weight
- model.stage4.2.branches.2.1.conv2.weight
- model.stage4.2.branches.2.2.conv1.weight
- model.stage4.2.branches.2.2.conv2.weight
- model.stage4.2.branches.2.3.conv1.weight
- model.stage4.2.branches.2.3.conv2.weight
- model.stage4.2.branches.3.0.conv1.weight
- model.stage4.2.branches.3.0.conv2.weight
- model.stage4.2.branches.3.1.conv1.weight
- model.stage4.2.branches.3.1.conv2.weight
- model.stage4.2.branches.3.2.conv1.weight
- model.stage4.2.branches.3.2.conv2.weight
- model.stage4.2.branches.3.3.conv1.weight
- model.stage4.2.branches.3.3.conv2.weight
- model.stage4.2.fuse_layers.0.1.0.weight
- model.stage4.2.fuse_layers.0.2.0.weight
- model.stage4.2.fuse_layers.0.3.0.weight
- model.stage4.2.fuse_layers.1.0.0.0.weight
- model.stage4.2.fuse_layers.1.2.0.weight
- model.stage4.2.fuse_layers.1.3.0.weight
- model.stage4.2.fuse_layers.2.0.0.0.weight
- model.stage4.2.fuse_layers.2.0.1.0.weight
- model.stage4.2.fuse_layers.2.1.0.0.weight
- model.stage4.2.fuse_layers.2.3.0.weight
- model.stage4.2.fuse_layers.3.0.0.0.weight
- model.stage4.2.fuse_layers.3.0.1.0.weight
- model.stage4.2.fuse_layers.3.0.2.0.weight
- model.stage4.2.fuse_layers.3.1.0.0.weight
- model.stage4.2.fuse_layers.3.1.1.0.weight
- model.stage4.2.fuse_layers.3.2.0.0.weight
- model.last_layer.0.weight
- model.last_layer.0.bias
- model.last_layer.3.weight
- model.last_layer.3.bias