- net.class_token
- net.patch_embedding.weight
- net.patch_embedding.bias
- net.positional_embedding.pos_embedding
- net.transformer.blocks.0.attn.proj_q.weight
- net.transformer.blocks.0.attn.proj_q.bias
- net.transformer.blocks.0.attn.proj_k.weight
- net.transformer.blocks.0.attn.proj_k.bias
- net.transformer.blocks.0.attn.proj_v.weight
- net.transformer.blocks.0.attn.proj_v.bias
- net.transformer.blocks.0.proj.weight
- net.transformer.blocks.0.proj.bias
- net.transformer.blocks.0.norm1.weight
- net.transformer.blocks.0.norm1.bias
- net.transformer.blocks.0.pwff.fc1.weight
- net.transformer.blocks.0.pwff.fc1.bias
- net.transformer.blocks.0.pwff.fc2.weight
- net.transformer.blocks.0.pwff.fc2.bias
- net.transformer.blocks.0.norm2.weight
- net.transformer.blocks.0.norm2.bias
- net.transformer.blocks.1.attn.proj_q.weight
- net.transformer.blocks.1.attn.proj_q.bias
- net.transformer.blocks.1.attn.proj_k.weight
- net.transformer.blocks.1.attn.proj_k.bias
- net.transformer.blocks.1.attn.proj_v.weight
- net.transformer.blocks.1.attn.proj_v.bias
- net.transformer.blocks.1.proj.weight
- net.transformer.blocks.1.proj.bias
- net.transformer.blocks.1.norm1.weight
- net.transformer.blocks.1.norm1.bias
- net.transformer.blocks.1.pwff.fc1.weight
- net.transformer.blocks.1.pwff.fc1.bias
- net.transformer.blocks.1.pwff.fc2.weight
- net.transformer.blocks.1.pwff.fc2.bias
- net.transformer.blocks.1.norm2.weight
- net.transformer.blocks.1.norm2.bias
- net.transformer.blocks.2.attn.proj_q.weight
- net.transformer.blocks.2.attn.proj_q.bias
- net.transformer.blocks.2.attn.proj_k.weight
- net.transformer.blocks.2.attn.proj_k.bias
- net.transformer.blocks.2.attn.proj_v.weight
- net.transformer.blocks.2.attn.proj_v.bias
- net.transformer.blocks.2.proj.weight
- net.transformer.blocks.2.proj.bias
- net.transformer.blocks.2.norm1.weight
- net.transformer.blocks.2.norm1.bias
- net.transformer.blocks.2.pwff.fc1.weight
- net.transformer.blocks.2.pwff.fc1.bias
- net.transformer.blocks.2.pwff.fc2.weight
- net.transformer.blocks.2.pwff.fc2.bias
- net.transformer.blocks.2.norm2.weight
- net.transformer.blocks.2.norm2.bias
- net.transformer.blocks.3.attn.proj_q.weight
- net.transformer.blocks.3.attn.proj_q.bias
- net.transformer.blocks.3.attn.proj_k.weight
- net.transformer.blocks.3.attn.proj_k.bias
- net.transformer.blocks.3.attn.proj_v.weight
- net.transformer.blocks.3.attn.proj_v.bias
- net.transformer.blocks.3.proj.weight
- net.transformer.blocks.3.proj.bias
- net.transformer.blocks.3.norm1.weight
- net.transformer.blocks.3.norm1.bias
- net.transformer.blocks.3.pwff.fc1.weight
- net.transformer.blocks.3.pwff.fc1.bias
- net.transformer.blocks.3.pwff.fc2.weight
- net.transformer.blocks.3.pwff.fc2.bias
- net.transformer.blocks.3.norm2.weight
- net.transformer.blocks.3.norm2.bias
- net.transformer.blocks.4.attn.proj_q.weight
- net.transformer.blocks.4.attn.proj_q.bias
- net.transformer.blocks.4.attn.proj_k.weight
- net.transformer.blocks.4.attn.proj_k.bias
- net.transformer.blocks.4.attn.proj_v.weight
- net.transformer.blocks.4.attn.proj_v.bias
- net.transformer.blocks.4.proj.weight
- net.transformer.blocks.4.proj.bias
- net.transformer.blocks.4.norm1.weight
- net.transformer.blocks.4.norm1.bias
- net.transformer.blocks.4.pwff.fc1.weight
- net.transformer.blocks.4.pwff.fc1.bias
- net.transformer.blocks.4.pwff.fc2.weight
- net.transformer.blocks.4.pwff.fc2.bias
- net.transformer.blocks.4.norm2.weight
- net.transformer.blocks.4.norm2.bias
- net.transformer.blocks.5.attn.proj_q.weight
- net.transformer.blocks.5.attn.proj_q.bias
- net.transformer.blocks.5.attn.proj_k.weight
- net.transformer.blocks.5.attn.proj_k.bias
- net.transformer.blocks.5.attn.proj_v.weight
- net.transformer.blocks.5.attn.proj_v.bias
- net.transformer.blocks.5.proj.weight
- net.transformer.blocks.5.proj.bias
- net.transformer.blocks.5.norm1.weight
- net.transformer.blocks.5.norm1.bias
- net.transformer.blocks.5.pwff.fc1.weight
- net.transformer.blocks.5.pwff.fc1.bias
- net.transformer.blocks.5.pwff.fc2.weight
- net.transformer.blocks.5.pwff.fc2.bias
- net.transformer.blocks.5.norm2.weight
- net.transformer.blocks.5.norm2.bias
- net.transformer.blocks.6.attn.proj_q.weight
- net.transformer.blocks.6.attn.proj_q.bias
- net.transformer.blocks.6.attn.proj_k.weight
- net.transformer.blocks.6.attn.proj_k.bias
- net.transformer.blocks.6.attn.proj_v.weight
- net.transformer.blocks.6.attn.proj_v.bias
- net.transformer.blocks.6.proj.weight
- net.transformer.blocks.6.proj.bias
- net.transformer.blocks.6.norm1.weight
- net.transformer.blocks.6.norm1.bias
- net.transformer.blocks.6.pwff.fc1.weight
- net.transformer.blocks.6.pwff.fc1.bias
- net.transformer.blocks.6.pwff.fc2.weight
- net.transformer.blocks.6.pwff.fc2.bias
- net.transformer.blocks.6.norm2.weight
- net.transformer.blocks.6.norm2.bias
- net.transformer.blocks.7.attn.proj_q.weight
- net.transformer.blocks.7.attn.proj_q.bias
- net.transformer.blocks.7.attn.proj_k.weight
- net.transformer.blocks.7.attn.proj_k.bias
- net.transformer.blocks.7.attn.proj_v.weight
- net.transformer.blocks.7.attn.proj_v.bias
- net.transformer.blocks.7.proj.weight
- net.transformer.blocks.7.proj.bias
- net.transformer.blocks.7.norm1.weight
- net.transformer.blocks.7.norm1.bias
- net.transformer.blocks.7.pwff.fc1.weight
- net.transformer.blocks.7.pwff.fc1.bias
- net.transformer.blocks.7.pwff.fc2.weight
- net.transformer.blocks.7.pwff.fc2.bias
- net.transformer.blocks.7.norm2.weight
- net.transformer.blocks.7.norm2.bias
- net.transformer.blocks.8.attn.proj_q.weight
- net.transformer.blocks.8.attn.proj_q.bias
- net.transformer.blocks.8.attn.proj_k.weight
- net.transformer.blocks.8.attn.proj_k.bias
- net.transformer.blocks.8.attn.proj_v.weight
- net.transformer.blocks.8.attn.proj_v.bias
- net.transformer.blocks.8.proj.weight
- net.transformer.blocks.8.proj.bias
- net.transformer.blocks.8.norm1.weight
- net.transformer.blocks.8.norm1.bias
- net.transformer.blocks.8.pwff.fc1.weight
- net.transformer.blocks.8.pwff.fc1.bias
- net.transformer.blocks.8.pwff.fc2.weight
- net.transformer.blocks.8.pwff.fc2.bias
- net.transformer.blocks.8.norm2.weight
- net.transformer.blocks.8.norm2.bias
- net.transformer.blocks.9.attn.proj_q.weight
- net.transformer.blocks.9.attn.proj_q.bias
- net.transformer.blocks.9.attn.proj_k.weight
- net.transformer.blocks.9.attn.proj_k.bias
- net.transformer.blocks.9.attn.proj_v.weight
- net.transformer.blocks.9.attn.proj_v.bias
- net.transformer.blocks.9.proj.weight
- net.transformer.blocks.9.proj.bias
- net.transformer.blocks.9.norm1.weight
- net.transformer.blocks.9.norm1.bias
- net.transformer.blocks.9.pwff.fc1.weight
- net.transformer.blocks.9.pwff.fc1.bias
- net.transformer.blocks.9.pwff.fc2.weight
- net.transformer.blocks.9.pwff.fc2.bias
- net.transformer.blocks.9.norm2.weight
- net.transformer.blocks.9.norm2.bias
- net.transformer.blocks.10.attn.proj_q.weight
- net.transformer.blocks.10.attn.proj_q.bias
- net.transformer.blocks.10.attn.proj_k.weight
- net.transformer.blocks.10.attn.proj_k.bias
- net.transformer.blocks.10.attn.proj_v.weight
- net.transformer.blocks.10.attn.proj_v.bias
- net.transformer.blocks.10.proj.weight
- net.transformer.blocks.10.proj.bias
- net.transformer.blocks.10.norm1.weight
- net.transformer.blocks.10.norm1.bias
- net.transformer.blocks.10.pwff.fc1.weight
- net.transformer.blocks.10.pwff.fc1.bias
- net.transformer.blocks.10.pwff.fc2.weight
- net.transformer.blocks.10.pwff.fc2.bias
- net.transformer.blocks.10.norm2.weight
- net.transformer.blocks.10.norm2.bias
- net.transformer.blocks.11.attn.proj_q.weight
- net.transformer.blocks.11.attn.proj_q.bias
- net.transformer.blocks.11.attn.proj_k.weight
- net.transformer.blocks.11.attn.proj_k.bias
- net.transformer.blocks.11.attn.proj_v.weight
- net.transformer.blocks.11.attn.proj_v.bias
- net.transformer.blocks.11.proj.weight
- net.transformer.blocks.11.proj.bias
- net.transformer.blocks.11.norm1.weight
- net.transformer.blocks.11.norm1.bias
- net.transformer.blocks.11.pwff.fc1.weight
- net.transformer.blocks.11.pwff.fc1.bias
- net.transformer.blocks.11.pwff.fc2.weight
- net.transformer.blocks.11.pwff.fc2.bias
- net.transformer.blocks.11.norm2.weight
- net.transformer.blocks.11.norm2.bias
- net.norm.weight
- net.norm.bias
- net.fc.weight
- net.fc.bias