- vgg.features.0.weight
- vgg.features.0.bias
- vgg.features.1.weight
- vgg.features.1.bias
- vgg.features.3.weight
- vgg.features.3.bias
- vgg.features.4.weight
- vgg.features.4.bias
- vgg.features.7.weight
- vgg.features.7.bias
- vgg.features.8.weight
- vgg.features.8.bias
- vgg.features.10.weight
- vgg.features.10.bias
- vgg.features.11.weight
- vgg.features.11.bias
- vgg.features.14.weight
- vgg.features.14.bias
- vgg.features.15.weight
- vgg.features.15.bias
- vgg.features.17.weight
- vgg.features.17.bias
- vgg.features.18.weight
- vgg.features.18.bias
- vgg.features.20.weight
- vgg.features.20.bias
- vgg.features.21.weight
- vgg.features.21.bias
- vgg.features.24.weight
- vgg.features.24.bias
- vgg.features.25.weight
- vgg.features.25.bias
- vgg.features.27.weight
- vgg.features.27.bias
- vgg.features.28.weight
- vgg.features.28.bias
- vgg.features.30.weight
- vgg.features.30.bias
- vgg.features.31.weight
- vgg.features.31.bias
- vgg.features.34.weight
- vgg.features.34.bias
- vgg.features.35.weight
- vgg.features.35.bias
- vgg.features.37.weight
- vgg.features.37.bias
- vgg.features.38.weight
- vgg.features.38.bias
- vgg.features.40.weight
- vgg.features.40.bias
- vgg.features.41.weight
- vgg.features.41.bias
- vgg.classifier.0.weight
- vgg.classifier.0.bias
- vgg.classifier.3.weight
- vgg.classifier.3.bias
- vgg.classifier.6.weight
- vgg.classifier.6.bias