- net.encoder.conv1.weight
- net.encoder.bn1.weight
- net.encoder.bn1.bias
- net.encoder.layer1.0.conv1.weight
- net.encoder.layer1.0.bn1.weight
- net.encoder.layer1.0.bn1.bias
- net.encoder.layer1.0.conv2.weight
- net.encoder.layer1.0.bn2.weight
- net.encoder.layer1.0.bn2.bias
- net.encoder.layer1.1.conv1.weight
- net.encoder.layer1.1.bn1.weight
- net.encoder.layer1.1.bn1.bias
- net.encoder.layer1.1.conv2.weight
- net.encoder.layer1.1.bn2.weight
- net.encoder.layer1.1.bn2.bias
- net.encoder.layer2.0.conv1.weight
- net.encoder.layer2.0.bn1.weight
- net.encoder.layer2.0.bn1.bias
- net.encoder.layer2.0.conv2.weight
- net.encoder.layer2.0.bn2.weight
- net.encoder.layer2.0.bn2.bias
- net.encoder.layer2.0.downsample.0.weight
- net.encoder.layer2.0.downsample.1.weight
- net.encoder.layer2.0.downsample.1.bias
- net.encoder.layer2.1.conv1.weight
- net.encoder.layer2.1.bn1.weight
- net.encoder.layer2.1.bn1.bias
- net.encoder.layer2.1.conv2.weight
- net.encoder.layer2.1.bn2.weight
- net.encoder.layer2.1.bn2.bias
- net.encoder.layer3.0.conv1.weight
- net.encoder.layer3.0.bn1.weight
- net.encoder.layer3.0.bn1.bias
- net.encoder.layer3.0.conv2.weight
- net.encoder.layer3.0.bn2.weight
- net.encoder.layer3.0.bn2.bias
- net.encoder.layer3.0.downsample.0.weight
- net.encoder.layer3.0.downsample.1.weight
- net.encoder.layer3.0.downsample.1.bias
- net.encoder.layer3.1.conv1.weight
- net.encoder.layer3.1.bn1.weight
- net.encoder.layer3.1.bn1.bias
- net.encoder.layer3.1.conv2.weight
- net.encoder.layer3.1.bn2.weight
- net.encoder.layer3.1.bn2.bias
- net.encoder.layer4.0.conv1.weight
- net.encoder.layer4.0.bn1.weight
- net.encoder.layer4.0.bn1.bias
- net.encoder.layer4.0.conv2.weight
- net.encoder.layer4.0.bn2.weight
- net.encoder.layer4.0.bn2.bias
- net.encoder.layer4.0.downsample.0.weight
- net.encoder.layer4.0.downsample.1.weight
- net.encoder.layer4.0.downsample.1.bias
- net.encoder.layer4.1.conv1.weight
- net.encoder.layer4.1.bn1.weight
- net.encoder.layer4.1.bn1.bias
- net.encoder.layer4.1.conv2.weight
- net.encoder.layer4.1.bn2.weight
- net.encoder.layer4.1.bn2.bias
- net.decoder.blocks.0.conv1.0.weight
- net.decoder.blocks.0.conv1.1.weight
- net.decoder.blocks.0.conv1.1.bias
- net.decoder.blocks.0.conv2.0.weight
- net.decoder.blocks.0.conv2.1.weight
- net.decoder.blocks.0.conv2.1.bias
- net.decoder.blocks.1.conv1.0.weight
- net.decoder.blocks.1.conv1.1.weight
- net.decoder.blocks.1.conv1.1.bias
- net.decoder.blocks.1.conv2.0.weight
- net.decoder.blocks.1.conv2.1.weight
- net.decoder.blocks.1.conv2.1.bias
- net.decoder.blocks.2.conv1.0.weight
- net.decoder.blocks.2.conv1.1.weight
- net.decoder.blocks.2.conv1.1.bias
- net.decoder.blocks.2.conv2.0.weight
- net.decoder.blocks.2.conv2.1.weight
- net.decoder.blocks.2.conv2.1.bias
- net.decoder.blocks.3.conv1.0.weight
- net.decoder.blocks.3.conv1.1.weight
- net.decoder.blocks.3.conv1.1.bias
- net.decoder.blocks.3.conv2.0.weight
- net.decoder.blocks.3.conv2.1.weight
- net.decoder.blocks.3.conv2.1.bias
- net.decoder.blocks.4.conv1.0.weight
- net.decoder.blocks.4.conv1.1.weight
- net.decoder.blocks.4.conv1.1.bias
- net.decoder.blocks.4.conv2.0.weight
- net.decoder.blocks.4.conv2.1.weight
- net.decoder.blocks.4.conv2.1.bias
- net.segmentation_head.0.weight
- net.segmentation_head.0.bias